using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SharpSqlBuilder.Attributes;
using SharpSqlBuilder.Builders;
using SharpSqlBuilder.Extensions;
using SharpSqlBuilder.Maps;
using SharpSqlBuilder.Tests.Common;
using NUnit.Framework;

namespace SharpSqlBuilder.Tests
{
    [TestFixture]
    public class TestSqlBuilder
    {
        [Table("class1", Schema = "foo")]
        public class Class1
        {
            [Column("id")]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            public Guid Id { get; set; }

            [Column("auto")]
            [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
            public Guid Auto { get; set; }

            [Column("value1")] public int Value1 { get; set; }
            [Column("value2")] public string Value2 { get; set; }

            [Column("do_not_change")]
            [IgnoreUpdate]
            public DateTime DoNotChange { get; set; }
        }

        [Table("class2", Schema = "foo")]
        public class Class2
        {
            [Key] [Column("key")] public Guid Key { get; set; }

            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
            [Column("key_db_generated")]
            public int DbGeneratedKey { get; set; }

            [Column("db_generated")]
            [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
            public Guid DbGenerated { get; set; }

            [Column("value1")] public string Value1 { get; set; }
            [Column("value2")] public string Value2 { get; set; }
            [Column("code_generated")] public DateTime CodeGenerated { get; set; }

            [Column("do_not_change")]
            [IgnoreUpdate]
            public DateTime DoNotChange { get; set; }
        }

        public DbMap<Class1> Map1 = new DbMap<Class1>();
        public DbMap<Class2> Map2 = new DbMap<Class2>();


        private void Check(string expected, string actual)
        {
            Diff.Text(expected, actual, Sql.Normalize);
            Console.WriteLine("___________\nACTUAL\n");
            Console.WriteLine(actual);
            Console.WriteLine("___________\nEXPECTED\n");
            Console.WriteLine(actual);
            Assert.AreEqual(Sql.Normalize(expected), Sql.Normalize(actual));
        }

        [Test]
        public void SqlBuilder_Delete_Class1_EqualsExpected()
        {
            var map = Map1;
            var sqlOptions = new SqlOptions {Dialect = SqlDialect.Postgres95};
            var sqlBuilder = SqlBuilder.Delete.From(map).WhereKeysEquals().ReturnsAllValues();
            var actual = sqlBuilder.BuildSql(sqlOptions);
            var expected = @"
            DELETE FROM foo.class1
            WHERE
	            (@Id = class1.id)
            RETURNING id, auto, value1, value2, do_not_change
            ";
            Check(expected, actual);
        }

        [Test]
        public void SqlBuilder_Insert_EqualsExpected()
        {
            var map = Map2;
            var sqlOptions = new SqlOptions {Dialect = SqlDialect.Postgres95};
            var sqlBuilder = SqlBuilder.Insert.Into(map)
               .AllStaticValues()
               .OnKeysConflict()
               .DoUpdateAllStaticValues()
               .Where(map[m => m.CodeGenerated].Excluded().LessThan(map[m => m.CodeGenerated].Column()))
               .ReturnsAutoGeneratedValues();
            var actual = sqlBuilder.BuildSql(sqlOptions);
            var expected = @"
            INSERT INTO foo.class2
            (key, value1, value2, code_generated, do_not_change)
            VALUES (
                @Key,
                @Value1,
                @Value2,
                @CodeGenerated,
                @DoNotChange
            )
            ON CONFLICT (key, key_db_generated)
            DO UPDATE SET
                db_generated = EXCLUDED.db_generated,
                value1 = EXCLUDED.value1,
                value2 = EXCLUDED.value2,
                code_generated = EXCLUDED.code_generated,
                do_not_change = EXCLUDED.do_not_change
            WHERE
                (EXCLUDED.code_generated < class2.code_generated)
            RETURNING key_db_generated, db_generated
            ";
            Check(expected, actual);
        }

        [Test]
        public void SqlBuilder_Select_EqualsExpected()
        {
            var map = Map1;

            var order = new
            {
                Id = new OrderItem {Direction = OrderDirection.Asc, Index = 2},
                Value1 = new OrderItem {Direction = OrderDirection.Desc, Index = 1},
                DoNotChange = (OrderItem) null
            };
            var orderMap = OrderMap.FromOrder(map, order.GetType());
            var sqlFilter = SqlFilter.Construct(new {Ids = new[] {1, 2}, Value1 = "foo", Auto = (int?) null});

            var whereSql = new[]
            {
                Conditions.Or(sqlFilter[f => f.Ids].IsNull(), map[m => m.Id].EqualsAny(sqlFilter[f => f.Ids])),
                Conditions.Or(sqlFilter[f => f.Value1].IsNull(),
                    map[m => m.Value1].EqualsOne(sqlFilter[f => f.Value1]))
            };
            var sqlOptions = new SqlOptions {Dialect = SqlDialect.Postgres95};
            var sqlBuilder = SqlBuilder.Select()
               .Values(map)
               .From(map)
               .Where(whereSql)
               .Order(orderMap, order)
               .Offset(5)
               .LimitBy(10);


            var actual = sqlBuilder.BuildSql(sqlOptions);
            var expected = @"
            SELECT
              class1.id AS Id,
              class1.auto AS Auto,
              class1.value1 AS Value1,
              class1.value2 AS Value2,
              class1.do_not_change AS DoNotChange
            FROM foo.class1
            WHERE
                   (@Ids IS NULL OR class1.id = ANY(@Ids))
               AND (@Value1 IS NULL OR class1.value1 = @Value1)
            ORDER BY
              class1.value1 DESC,
              class1.id ASC
            OFFSET 5
            LIMIT 10
            ";
            Check(expected, actual);
        }

        [Test]
        public void SqlBuilder_SelectMultiple_EqualsExpected()
        {
            var map1 = Map1;
            var map2 = Map2;
            var order = new
            {
                Id = new OrderItem {Direction = OrderDirection.Asc, Index = 2},
                Value1 = new OrderItem {Direction = OrderDirection.Desc, Index = 1},
                DoNotChange = (OrderItem) null
            };
            var orderMap = OrderMap.FromOrder(map1, order.GetType());
            var sqlFilter = SqlFilter.Construct(new
            {
                Ids = new[] {1, 2},
                Value1 = "foo",
                Auto = (int?) null,
                Key = Guid.Empty,
                DbGeneratedKey = 2
            });
            var whereSql = new[]
            {
                Conditions.Or(sqlFilter[f => f.Ids].IsNull(), map1[m => m.Id].EqualsAny(sqlFilter[f => f.Ids])),
                Conditions.Or(sqlFilter[f => f.Value1].IsNull(),
                    map1[m => m.Value1].EqualsOne(sqlFilter[f => f.Value1])),
                Conditions.Or(sqlFilter[f => f.Key].IsNull(), map2[m => m.Key].EqualsOne(sqlFilter[f => f.Key])),
                sqlFilter[f => f.DbGeneratedKey]
                   .IsNull()
                   .Or(map2[m => m.DbGeneratedKey].EqualsOne(sqlFilter[f => f.DbGeneratedKey]))
            };

            var sqlBuilder = SqlBuilder.Select()
               .Values(map1, map2)
               .From(map1)
               .InnerJoin(map2, map2[m => m.Key].EqualsOne(map1[m => m.Id]))
               .Where(whereSql)
               .Order(orderMap, order)
               .LimitBy((long?) null);
            var sqlOptions = new SqlOptions {Dialect = SqlDialect.Postgres95};

            var actual = sqlBuilder.BuildSql(sqlOptions);
            var expected = @"
            SELECT
	            class1.id AS Id,
	            class1.auto AS Auto,
	            class1.value1 AS Value1,
	            class1.value2 AS Value2,
	            class1.do_not_change AS DoNotChange,
	            class2.key AS Key,
	            class2.key_db_generated AS DbGeneratedKey,
	            class2.db_generated AS DbGenerated,
	            class2.value1 AS Value1,
	            class2.value2 AS Value2,
	            class2.code_generated AS CodeGenerated,
	            class2.do_not_change AS DoNotChange
            FROM foo.class1
            INNER JOIN foo.class2 ON class2.key = class1.id
            WHERE
	                 (@Ids IS NULL OR class1.id = ANY(@Ids))
	             AND (@Value1 IS NULL OR class1.value1 = @Value1)
	             AND (@Key IS NULL OR class2.key = @Key)
	             AND (@DbGeneratedKey IS NULL OR class2.key_db_generated = @DbGeneratedKey)
            ORDER BY
	            class1.value1 DESC,
	            class1.id ASC
            ";
            Check(expected, actual);
        }

        [Test]
        public void SqlBuilder_Update_Class1_EqualsExpected()
        {
            var map = Map1;
            var sqlBuilder = SqlBuilder.Update(map).AllUpdatableValues().WhereKeysEquals().ReturnsAutoGeneratedKeys();
            var actual = sqlBuilder.ToString();
            var expected = @"
            UPDATE foo.class1
            SET
	            value1 = @Value1,
	            value2 = @Value2
            WHERE
	            (@Id = class1.id)
            RETURNING id, auto
            ";
            Check(expected, actual);
        }
    }
}