using System;
using System.Collections.Generic;
using System.Text;
using SharpSqlBuilder.Maps;
using SharpSqlBuilder.Operators;

namespace SharpSqlBuilder.Builders
{

    public class SqlDeleteBuilderHelper<TBuilder> : SqlDeleteBuilderBase where TBuilder : SqlDeleteBuilderBase
    {
        public SqlDeleteBuilderHelper(SqlTable sqlTable) : base(sqlTable)
        {
        }
        public TBuilder CustomSql(string customSql, SqlDeletePosition? type = null) => (TBuilder)base.CustomSql(customSql, type);
        protected TBuilder Where(params Operator[] operators) => (TBuilder)base.Where(operators);
        protected TBuilder Where(IEnumerable<Operator> operators) => (TBuilder)base.Where(operators);
        public TBuilder WhereKeysEquals() => (TBuilder)base.WhereKeysEquals();
        public TBuilder ReturnsAutoGeneratedKeys() => (TBuilder)base.ReturnsAutoGeneratedKeys();
        public TBuilder ReturnsAllValues() => (TBuilder)base.ReturnsAllValues();
        protected TBuilder Returns(IEnumerable<SqlColumn> sqlColumns) => (TBuilder)base.Returns(sqlColumns);
    }
}
