using System;
using System.Collections.Generic;
using System.Linq;
using SharpSqlBuilder.Blocks;
using SharpSqlBuilder.Entities;
using SharpSqlBuilder.Extensions;
using SharpSqlBuilder.Maps;
using SharpSqlBuilder.Operators;

namespace SharpSqlBuilder.Builders
{
    public class SqlUpdateBuilder : SqlBuilderBase
    {
        protected readonly UpdateColumnsBlock ColumnsBlock = new UpdateColumnsBlock();

        protected readonly Dictionary<SqlUpdatePosition, CustomSqlBlock> CustomBlocks =
            new Dictionary<SqlUpdatePosition, CustomSqlBlock>
            {
                {SqlUpdatePosition.Start, new CustomSqlBlock()},
                {SqlUpdatePosition.Table, new CustomSqlBlock()},
                {SqlUpdatePosition.Columns, new CustomSqlBlock()},
                {SqlUpdatePosition.Where, new CustomSqlBlock()},
                {SqlUpdatePosition.Return, new CustomSqlBlock()}
            };

        protected readonly SqlTable SqlTable;
        protected readonly ReturningBlock ReturningsBlock = new ReturningBlock();
        protected readonly UpdateTableBlock UpdateTableBlock;
        protected readonly WhereBlock WhereBlock = new WhereBlock();
        protected SqlUpdatePosition CurrentPosition = SqlUpdatePosition.Start;

        public SqlUpdateBuilder(SqlTable sqlTable)
        {
            SqlTable = sqlTable;
            UpdateTableBlock = new UpdateTableBlock(sqlTable ?? throw new ArgumentException(nameof(sqlTable)));
        }

        public override bool Present(SqlOptions sqlOptions) =>
            UpdateTableBlock?.Present(sqlOptions) == true && ColumnsBlock.Present(sqlOptions);

        public SqlUpdateBuilder CustomSql(string customSql, SqlUpdatePosition? type = null)
        {
            var customSelectType = type ?? CurrentPosition;
            var block = CustomBlocks[customSelectType];
            block.Add(new SqlCustomSqlBlock(customSql));
            return this;
        }


        public SqlUpdateBuilder Values(IEnumerable<SqlColumn> dbMapItems)
        {
            ColumnsBlock.AddRange(dbMapItems.Select(m => new UpdateColumnBlock(m)));
            CurrentPosition = SqlUpdatePosition.Columns;
            return this;
        }

        public SqlUpdateBuilder AllUpdatableValues() => Values(SqlTable.UpdatableColumns);

        public SqlUpdateBuilder Where(params Operator[] operators) => Where((IEnumerable<Operator>) operators);

        public SqlUpdateBuilder Where(IEnumerable<Operator> operators)
        {
            WhereBlock.AddRange(operators);
            CurrentPosition = SqlUpdatePosition.Where;
            return this;
        }

        public SqlUpdateBuilder WhereKeysEquals()
        {
            return Where(SqlTable.Keys.Select(m => m.Property().EqualsOne(m.Column())));
        }

        public SqlUpdateBuilder ReturnsAutoGeneratedKeys() => Returns(SqlTable.AutoGeneratedColumns);

        public SqlUpdateBuilder ReturnsAllValues() => Returns(SqlTable);

        public SqlUpdateBuilder Returns(IEnumerable<SqlColumn> dbMapItems)
        {
            ReturningsBlock.AddRange(dbMapItems.Select(m => new ColumnEntity(m)));
            CurrentPosition = SqlUpdatePosition.Return;
            return this;
        }

        public override string BuildSql(SqlOptions sqlOptions)
        {
            if (sqlOptions == null)
                throw new ArgumentException(nameof(sqlOptions));

            CheckBeforeBuild(sqlOptions);

            IEnumerable<SqlBuilderEntity> data = new SqlBuilderEntity[]
            {
                CustomBlocks[SqlUpdatePosition.Start],
                UpdateTableBlock,
                CustomBlocks[SqlUpdatePosition.Table],
                ColumnsBlock,
                CustomBlocks[SqlUpdatePosition.Columns],
                WhereBlock,
                CustomBlocks[SqlUpdatePosition.Where],
                ReturningsBlock,
                CustomBlocks[SqlUpdatePosition.Return]
            };
            var commands = data.Where(b => CheckBlock(b, sqlOptions)).Select(b => b.BuildSql(sqlOptions));
            return string.Join(sqlOptions.NewLine(), commands);
        }
    }
}