namespace SharpSqlBuilder.Maps
{
    public class DbMapItem
    {
        public bool IsKey { get; set; }
        public bool Update { get; set; } = true;
        public bool AutoGenerated { get; set; }
        public string ColumnName { get; set; }
        public string PropertyName { get; set; }
        public DbMap Parent { get; set; }

        public DbMapItem Key()
        {
            IsKey = true;
            return DoNotUpdate();
        }

        public DbMapItem DoNotUpdate()
        {
            Update = false;
            return this;
        }

        public DbMapItem Auto()
        {
            AutoGenerated = true;
            return this;
        }
    }
}