namespace SharpSqlBuilder.Maps
{
    public class SqlColumn
    {
        public bool IsKey { get; set; }
        public bool Update { get; set; } = true;
        public bool AutoGenerated { get; set; }
        public string ColumnName { get; set; }
        public string PropertyName { get; set; }
        public SqlTable Parent { get; set; }

        public SqlColumn Key()
        {
            IsKey = true;
            return DoNotUpdate();
        }

        public SqlColumn DoNotUpdate()
        {
            Update = false;
            return this;
        }

        public SqlColumn Auto()
        {
            AutoGenerated = true;
            return this;
        }
    }
}