using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using SharpSqlBuilder.Attributes;
using SharpSqlBuilder.Extensions;

namespace SharpSqlBuilder.Maps
{
    public class SqlTable : IEnumerable<SqlColumn>
    {
        public static string DefaultSchema;
        protected readonly IList<SqlColumn> Columns = new List<SqlColumn>();
        protected readonly IDictionary<string, SqlColumn> ColumnsDictionary = new Dictionary<string, SqlColumn>();
        public readonly string Schema;
        public readonly string TableName;
        private static readonly ConcurrentDictionary<Type, SqlTable> Tables = new ConcurrentDictionary<Type, SqlTable>();

        public SqlTable(string schema, string tableName)
        {
            TableName = tableName ?? throw new ArgumentException(nameof(tableName));
            Schema = schema ?? DefaultSchema;
        }

        public static SqlTable<T> ForType<T>()
        {
            var r = Tables.GetOrAdd(typeof(SqlTable<T>), type => new SqlTable<T>());
            return (SqlTable<T>)r;
        }
        public SqlColumn FirstColumn => Columns.FirstOrDefault();
        public IEnumerable<SqlColumn> ForeignKeys => Columns.Where(v => v.ForeignKey!=null);
        public IEnumerable<SqlColumn> AutoGeneratedColumns => Columns.Where(v => v.IsAutoGenerated);
        public IEnumerable<SqlColumn> Keys => Columns.Where(v => v.IsKey);
        public IEnumerable<SqlColumn> NotKeys => Columns.Where(v => !v.IsKey);
        public IEnumerable<SqlColumn> StaticColumns => Columns.Where(v => !v.IsAutoGenerated);
        public IEnumerable<SqlColumn> UpdatableColumns => Columns.Where(v => !v.IsAutoGenerated && !v.IsKey && v.IsUpdatable);

        public SqlColumn this[string property] => ColumnsDictionary[property];

        IEnumerator<SqlColumn> IEnumerable<SqlColumn>.GetEnumerator() => Columns.GetEnumerator();

        public IEnumerator GetEnumerator() => ((IEnumerable) Columns).GetEnumerator();

        public void AddRange(IEnumerable<SqlColumn> items)
        {
            foreach (var sqlColumn in items)
                Add(sqlColumn);
        }

        public void Add(SqlColumn sqlColumn)
        {
            ColumnsDictionary.Add(sqlColumn.PropertyName, sqlColumn);
            Columns.Add(sqlColumn);
        }

        protected IEnumerable<SqlColumn> GetColumns(Type type)
        {
            var namingConvention = type.GetAttribute<NamingConventionAttribute>()?.NamingConvention ??
                NamingConvention.AsIs;
            return type.GetProperties()
               .Where(p => p.GetAttribute<SqlIgnore>() == null)
               .Select(p => new PropertySqlColumn(p, namingConvention) { Parent = this });
        }
    }


    public class SqlTable<T> : SqlTableTyped
    {
        public SqlTable() : base(typeof(T))
        {
        }

        public SqlColumn this[Expression<Func<T, object>> exp] => base[exp.GetPropertyInfo().Name];
    }
}